### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by alfredrumss** [Fur6y/heartbeat-monitor#1]
Do you have some repository when the heart rate working up on the latest version react native ?

**Comment by fabianfetting** [comment]
Sry i dont have a repo with a updated react native version. Unfortunately at the moment i havn't time to update the repo to a newer react native version. But feel free to send a pull request.

**Comment by fabianfetting** [comment]
Hey @alfredrumss,
great news. I found some time to upgrade the project to the newest react-native version 0.55.2. Checkout the repo. Hope it helps.
